// Color Thresholder 2.16.0/1.54p
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("Duplicate...", "title=tissue_mask_tmp");
run("8-bit");
setThreshold(15, 255);
run("Convert to Mask");
run("Fill Holes");
run("Create Selection");
roiManager("Add");
close("tissue_mask_tmp");
selectWindow(a);
roiManager("Select", 0);
run("Clear Outside");
run("Select None");
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=2;
max[0]=228;
filter[0]="stop";
min[1]=58;
max[1]=255;
filter[1]="pass";
min[2]=161;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
roiManager("Select", 0);
run("Analyze Particles...", "size=1-1000 display summarize");
roiManager("Reset");